version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=users_user
      - POSTGRES_PASSWORD=users_password
      - POSTGRES_DB=users_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
